tunnel: 92182b8a-47fa-480c-9ff1-82468b23f648
credentials-file: C:\Users\Admin\.cloudflared\92182b8a-47fa-480c-9ff1-82468b23f648.json
ingress:
  - hostname: jellyfin.mzxt.eu
    service: http://localhost:8096
  - hostname: radarr.mzxt.eu
    service: http://localhost:7878
  - hostname: sonarr.mzxt.eu
    service: http://localhost:8989
  - hostname: qbit.mzxt.eu
    service: http://localhost:7474
  - hostname: prowlarr.mzxt.eu
    service: http://localhost:9696
  - hostname: apps.mzxt.eu
    service: http://localhost:80
  - hostname: send.mzxt.eu
    service: http://localhost:1119
    
  - service: http_status:404