tunnel: c6653f5f-c632-4063-b989-cc2276d6f389
credentials-file: C:\Users\Admin\.cloudflared\c6653f5f-c632-4063-b989-cc2276d6f389.json
ingress:
  - hostname: www.mzxt.in
    service: http://localhost:8096
  - hostname: play.mzxt.in
    service: http://localhost:8096
  - hostname: radarr.mzxt.in
    service: http://localhost:7878
  - hostname: sonarr.mzxt.in
    service: http://localhost:8989
  - hostname: qbit.mzxt.in
    service: http://localhost:7474
  - hostname: prowlarr.mzxt.in
    service: http://localhost:9696
  - hostname: apps.mzxt.in
    service: http://localhost:80
  - hostname: send.mzxt.in
    service: http://localhost:1119
  - hostname: jenkins.mzxt.in
    service: http://localhost:4714
  - hostname: system.mzxt.in
    service: http://localhost:2917
  - hostname: systemapi.mzxt.in
    service: http://localhost:2916

  - service: http_status:404
